# Agent OS Configuration

# Refer to the official Agent OS documentation at:
# https://buildermethods.com/agent-os

agent_os_version: 1.4.1

agents:
  claude_code:
    enabled: true
  cursor:
    enabled: false

project_types:
  default:
    instructions: ~/.agent-os/instructions
    standards: ~/.agent-os/standards

  # type_a:
  #   instructions: ~/.agent-os/project_types/type_a/instructions
  #   standards: ~/.agent-os/project_types/type_a/standards

  # type_b:
  #   instructions: ~/.agent-os/project_types/type_b/instructions
  #   standards: ~/.agent-os/project_types/type_b/standards

default_project_type: default

extensions:
  sandbox:
    enabled: true
    required: true        # Cannot be disabled
    symlink: true
  hooks:
    enabled: true         # Default for projects
    source_dir: "claude-code/hooks"  # Location of hook files
    install_dir: "~/.claude"   # Installation target
    update_settings: true
  peer:
    enabled: false # Default for projects
    nats_url: "nats://localhost:4222"
    project_buckets: true # Per-project KV buckets
